name: 🚑️ Skill issue
description: You have a problem with a skill
labels: ["bug"]
title: "[BUG]: "
body:
  - type: markdown
    attributes:
      value: |
        **Skill issues, feature requests and bugs don't belong belong in their own repositories, so the author is emailed with your request. Please submit your ticket in the adequate repository!**
        Thanks for taking the time to fill out this bug report 🤗
        Make sure there aren't any open/closed issues for this topic 😃
